apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ci-sonarqube-data-pvc
  annotations:
    volumeType: local
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ci-sonarqube-extensions-pvc
  annotations:
    volumeType: local
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ci-sonarqube-esdata-pvc
  annotations:
    volumeType: local
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-sonarqube-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-sonarqube-data
  template:
    metadata:
      labels:
        app: ci-sonarqube-data
    spec:
      securityContext:
        runAsUser: 999
      containers:
        - name: postgres
          image: docker.io/postgres:13.7
          resources:
            requests:
              cpu: "0.25"
              memory: "256Mi"
            limits:
              cpu: "0.5"
              memory: "512Mi"
          env:
            - name: POSTGRES_USER
              value: "sonarqube"
            - name: POSTGRES_PASSWORD
              value: "sonar99sonar"
            - name: "PGDATA"
              value: "/var/lib/postgresql/data/pg"
          volumeMounts:
            - name: ci-sonarqube-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: ci-sonarqube-data
          persistentVolumeClaim:
            claimName: ci-sonarqube-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ci-sonarqube-data
spec:
  selector:
    app: ci-sonarqube-data
  ports:
    - name: psql
      port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-sonarqube
  template:
    metadata:
      labels:
        app: ci-sonarqube
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      initContainers:
        - name: sysctl
          image: docker.io/busybox
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
      containers:
        - name: sonarqube
          image: docker.io/sonarqube:9.9.1-community
          #command: [ "sleep", "10000" ]
          resources:
            requests:
              cpu: "0.5"
              memory: "1024Mi"
            limits:
              cpu: "1"
              memory: "2048Mi"
          env:
            - name: SONAR_JDBC_URL
              value: "jdbc:postgresql://ci-sonarqube-data:5432/sonarqube?charSet=UNICODE"
            - name: SONAR_JDBC_USERNAME
              value: "sonarqube"
            - name: SONAR_JDBC_PASSWORD
              value: "sonar99sonar"
            - name: SONAR_WEB_CONTEXT
              value: "/sonarqube"
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
          volumeMounts:
            - name: ci-sonarqube-extensions
              mountPath: /opt/sonarqube/extensions
            - name: ci-sonarqube-esdata
              mountPath: /opt/sonarqube/data
      volumes:
        - name: ci-sonarqube-extensions
          persistentVolumeClaim:
            claimName: ci-sonarqube-extensions-pvc
        - name: ci-sonarqube-esdata
          persistentVolumeClaim:
            claimName: ci-sonarqube-esdata-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ci-sonarqube
spec:
  selector:
    app: ci-sonarqube
  ports:
    - name: web
      port: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ci-sonarqube
  annotations:
    spec.ingressClassName: traefik
spec:
  rules:
  - http:
      paths:
      - path: /sonarqube
        pathType: Prefix
        backend:
          service:
            name: ci-sonarqube
            port:
              number: 9000